# Generated by Django 3.1 on 2020-09-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
